title: KSR - KW Sportbike Racing trackdays at Grand Bend Motorplex
name: KSR - KW Sportbike Racing
email: kwsportracing@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  KW Sport Racing motorcycle track days in Ontario. KW Sport Racing Club / KW Sport Riding Club runs track days exclusively at Grand Bend Motorplex. Join us for our 2019 Track Days!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

instagram: https://www.instagram.com/ksrcanada/
facebook: https://www.facebook.com/groups/KWSportRacing/

registration: https://docs.google.com/forms/d/e/1FAIpQLScfz7XgnrlxyOeOVlHFwoxRIUfPBdQTzGLMAi_m5fYg02JSqQ/viewform

# Build settings
theme: minima
plugins:
  - jekyll-feed
